### PR TITLE
Add support for ssh authentication

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Sadly this PR requires more work as the default Values are really Github HTTP centric and would need more work than time I have available. Feel free to pick this up if you have time

**Comment by gianfranco-l** [comment]
@kubasobon can we considered  this solved given that we have now figured out a way to access private repos? cc @piontec

**Comment by mproffitt** [comment]
Re-opening this request as it still requires completing in order to support customers who wish to use `identity` keys after bootstrap rather than relying on Private Authentication Tokens

**Comment by gianfranco-l** [comment]
we as @giantswarm/team-honeybadger we decided to not support this because current solution is better suited for our current understanding of the use cases (tokens are much more secure than SSH identities)

**Comment by gianfranco-l** [comment]
@mproffitt will talk with the customer to see if there is valid customer use case for this

**Comment by mproffitt** [comment]
Customer is looking to see if they have existing automation accounts which can be used as a more secure solution

**Pull request closed without merging**
