### PR TITLE
Move back to creating CRDs with a job

### PR DESCRIPTION
**Pull request by uvegla**
This reverts commit 9183da0318758924b25a31fb3d724bf5c722b178.

See: https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/handle_crds_with_helm_3/

Can be tried out with:

```yaml
---
apiVersion: v1
data:
  values: |
    sources:
      - branch: master
        interval: 30s
        kind: GitRepository
        name: podinfo
        provider: github
        url: https://github.com/stefanprodan/podinfo
        credentials:
          username: << GITHUB_USERNAME >>
          password: << GITHUB_TOKEN_WITH_REPO_SCOPE >>

    kustomizations:
      - interval: 30s
        name: podinfo
        path: ./kustomize
        prune: true
        source_name: podinfo
        postBuild:
          substitute:
            cluster_domain: "MY_DOMAIN"
            cluster_name: "CAPI_WC_NAME"
            cluster_release: "0.8.1"
            default_apps_release: "0.2.0"
            organization: "ORG_NAME"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: flux-app-userconfig-ap99a
  namespace: ap99a
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: flux-app
  namespace: ap99a
spec:
  catalog: giantswarm-test
  kubeConfig:
    inCluster: false
  name: flux-app
  namespace: ap99a
  userConfig:
    configMap:
      name: flux-app-userconfig-ap99a
      namespace: ap99a
  version: 0.13.0-9887c74e9c7990a3cf2b9d9feeb326c7b1f8e7ef


```

### CODE REVIEW

**Comment by uvegla** [comment]
It seem to be working at the current state, however there is a problem. Upon uninstalling the Flux CRs and the Secret CRs created via the CR install job do not get deleted, which is not very nice.

**Comment by kubasobon** [comment]
@uvegla have you thought about adding [metadata.ownerReferences](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) to the resources that don't get cleaned up?
Also, if there is an automatic cleanup on uninstall, let's make extra sure it does not happen when the app is simply upgraded.

**Comment by uvegla** [comment]
> @uvegla have you thought about adding [metadata.ownerReferences](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) to the resources that don't get cleaned up? Also, if there is an automatic cleanup on uninstall, let's make extra sure it does not happen when the app is simply upgraded.

I was checking these docs:
- https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
- https://kubernetes.io/docs/concepts/architecture/garbage-collection/
- https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids

Adding for example this owner reference to an a `Provider` CR we create with the git source:

```yaml
 metadata:
  # ...
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    kind: Deployment
    name: source-controller
    uid: ff39e1be-8e36-483e-a140-7a91638ba5c
```

If we have that Kubernetes will garbage collect the `Provider` when that unique object of the `source-controller` is removed. The point is that unique object, so the issues are the following:
- the `uid` is assigned when the object is created so Helm does not know if beforehand. I think we could overcome this by moving the CR installation to a post deployment hook and do some kubectl magic to get the assigned UIDs, but it keeps adding to the complexity.
- In case during a Helm upgrade if the object is replaced / recreated it will make Kubernetes garbage collect the source / kustomization which could be bad / have unwanted side effects of deleting resources so I consider this to be very risky

**Comment by uvegla** [comment]
Based on the above and our discussions I am closing this PR in favour of: https://github.com/giantswarm/flux-app/pull/127

**Pull request closed without merging**
